services:
  job_processor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  swagger_ui: # use docker-image to serve swagger-ui: https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/installation.md#docker
    build:
      context: .
      dockerfile: Dockerfile.swaggerui
    ports:
      - "80:8080"
    environment:
      - BASE_URL=${BASE_URL}
      - SWAGGER_JSON=${SWAGGER_JSON}
